branches:
  only:
    - hugo-source 

install:
# 安装最新的hugo
  - sudo apt-get install hugo

script:
# 运行hugo命令
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: master
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: hugo-source
