baseURL = "https://yuifn.github.io"
languageCode = "en-us"
title = "Code |> Functional |> Fun"
theme = "yinwang"

[params]
	author = "Yui"
	github = "YuiFn"
	highlight = "xcode"
	langs  = ["rust", "go", "elixir", "scala", "ocaml", "dart", "haskell"]
	# googleAnalytics = "UA-129503268-1"
	baiduAnalytics = "37b4eec6344fe6048329351e0bff8f31"
	menus = true

[permalinks]
   post = "/:year/:month/:title/"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 10

[[menu.main]]
	name = "Github"
	url = "https://github.com/YuiFn"
[[menu.main]]
	name = "分类"
	url = "/categories/"
