baseURL = "https://yuifn.github.io"
languageCode = "en-us"
title = "Functional |> Concurrent |> Pragmatic |> Fun"
theme = "yinwang"

[params]
	author = "Yui"
	github = "YuiFn"
	highlight = "xcode"
	langs  = ["rust", "go", "elixir", "scala", "ocaml", "dart", "haskell"]
	googleAnalytics = "UA-129503268-1"
	menus = true

[permalinks]
   post = "/:year/:month/:title/"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 10
	
[[menu.main]]
	name = "Github"
	url = "https://yuifn.github.io"